/**
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * OpenAPI spec version: 6.5.2
 * Contact: contact@mailslurp.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class AITransformMappingProjection {
    'userId': string;
    'aiTransformId': string;
    'entityId': string;
    'entityType': AITransformMappingProjectionEntityTypeEnum;
    'contentSelector'?: AITransformMappingProjectionContentSelectorEnum;
    'triggerSelector'?: AITransformMappingProjectionTriggerSelectorEnum;
    'name'?: string;
    'id': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "aiTransformId",
            "baseName": "aiTransformId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "entityId",
            "baseName": "entityId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "entityType",
            "baseName": "entityType",
            "type": "AITransformMappingProjectionEntityTypeEnum",
            "format": ""
        },
        {
            "name": "contentSelector",
            "baseName": "contentSelector",
            "type": "AITransformMappingProjectionContentSelectorEnum",
            "format": ""
        },
        {
            "name": "triggerSelector",
            "baseName": "triggerSelector",
            "type": "AITransformMappingProjectionTriggerSelectorEnum",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        }    ];

    static getAttributeTypeMap() {
        return AITransformMappingProjection.attributeTypeMap;
    }
    
    public constructor() {
    }
}


export type AITransformMappingProjectionEntityTypeEnum = "INBOX" | "PHONE" ;
export type AITransformMappingProjectionContentSelectorEnum = "RAW" | "BODY" | "BODY_ATTACHMENTS" ;
export type AITransformMappingProjectionTriggerSelectorEnum = "PER_MESSAGE" | "PER_ATTACHMENT" ;

