/**
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * OpenAPI spec version: 6.5.2
 * Contact: contact@mailslurp.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

/**
* Connector
*/
export class ConnectorProjection {
    'id'?: string;
    'userId': string;
    'inboxId': string;
    'createdAt': Date;
    'connectorType': ConnectorProjectionConnectorTypeEnum;
    'syncScheduleType': ConnectorProjectionSyncScheduleTypeEnum;
    'syncInterval'?: number;
    'syncEnabled': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "inboxId",
            "baseName": "inboxId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "connectorType",
            "baseName": "connectorType",
            "type": "ConnectorProjectionConnectorTypeEnum",
            "format": ""
        },
        {
            "name": "syncScheduleType",
            "baseName": "syncScheduleType",
            "type": "ConnectorProjectionSyncScheduleTypeEnum",
            "format": ""
        },
        {
            "name": "syncInterval",
            "baseName": "syncInterval",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "syncEnabled",
            "baseName": "syncEnabled",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ConnectorProjection.attributeTypeMap;
    }
    
    public constructor() {
    }
}


export type ConnectorProjectionConnectorTypeEnum = "IMAP" ;
export type ConnectorProjectionSyncScheduleTypeEnum = "INTERVAL" ;

