/**
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * OpenAPI spec version: 6.5.2
 * Contact: contact@mailslurp.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

/**
* Options for creating automatic syncing between an inbox connection and an external mail provider
*/
export class CreateConnectorSyncSettingsOptions {
    /**
    * Enable automatic background sync
    */
    'syncEnabled'?: boolean;
    /**
    * Sync schedule type
    */
    'syncScheduleType'?: CreateConnectorSyncSettingsOptionsSyncScheduleTypeEnum;
    /**
    * Sync interval in minutes
    */
    'syncInterval'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "syncEnabled",
            "baseName": "syncEnabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "syncScheduleType",
            "baseName": "syncScheduleType",
            "type": "CreateConnectorSyncSettingsOptionsSyncScheduleTypeEnum",
            "format": ""
        },
        {
            "name": "syncInterval",
            "baseName": "syncInterval",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return CreateConnectorSyncSettingsOptions.attributeTypeMap;
    }
    
    public constructor() {
    }
}


export type CreateConnectorSyncSettingsOptionsSyncScheduleTypeEnum = "INTERVAL" ;

