/**
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * OpenAPI spec version: 6.5.2
 * Contact: contact@mailslurp.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

/**
* Options for IMAP connection to external email inbox. Allows syncing emails via IMAP.
*/
export class CreateConnectorImapConnectionOptions {
    'imapSsl'?: boolean;
    'imapUsername'?: string;
    'imapPassword'?: string;
    /**
    * Optional folder to select during IMAP connection
    */
    'selectFolder'?: string;
    'searchTerms'?: string;
    /**
    * IMAP server port
    */
    'imapPort'?: number;
    /**
    * IMAP server host
    */
    'imapHost': string;
    /**
    * IMAP server enabled
    */
    'enabled'?: boolean;
    'startTls'?: boolean;
    'proxyEnabled'?: boolean;
    'proxyPort'?: number;
    'proxyHost'?: string;
    'localHostName'?: string;
    /**
    * List of IMAP mechanisms
    */
    'mechanisms'?: Array<string>;
    'sslTrust'?: string;
    /**
    * List of SSL protocols
    */
    'sslProtocols'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "imapSsl",
            "baseName": "imapSsl",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "imapUsername",
            "baseName": "imapUsername",
            "type": "string",
            "format": ""
        },
        {
            "name": "imapPassword",
            "baseName": "imapPassword",
            "type": "string",
            "format": ""
        },
        {
            "name": "selectFolder",
            "baseName": "selectFolder",
            "type": "string",
            "format": ""
        },
        {
            "name": "searchTerms",
            "baseName": "searchTerms",
            "type": "string",
            "format": ""
        },
        {
            "name": "imapPort",
            "baseName": "imapPort",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "imapHost",
            "baseName": "imapHost",
            "type": "string",
            "format": ""
        },
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "startTls",
            "baseName": "startTls",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "proxyEnabled",
            "baseName": "proxyEnabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "proxyPort",
            "baseName": "proxyPort",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "proxyHost",
            "baseName": "proxyHost",
            "type": "string",
            "format": ""
        },
        {
            "name": "localHostName",
            "baseName": "localHostName",
            "type": "string",
            "format": ""
        },
        {
            "name": "mechanisms",
            "baseName": "mechanisms",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "sslTrust",
            "baseName": "sslTrust",
            "type": "string",
            "format": ""
        },
        {
            "name": "sslProtocols",
            "baseName": "sslProtocols",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateConnectorImapConnectionOptions.attributeTypeMap;
    }
    
    public constructor() {
    }
}

