/**
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * OpenAPI spec version: 6.5.2
 * Contact: contact@mailslurp.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EmailRecipients } from './EmailRecipients.ts';
import { Sender } from './Sender.ts';
import { HttpFile } from '../http/http.ts';

export class EmailThreadDto {
    /**
    * ID of email thread
    */
    'id': string;
    /**
    * User ID
    */
    'userId': string;
    /**
    * Inbox ID
    */
    'inboxId'?: string;
    /**
    * From sender
    */
    'from'?: string;
    /**
    * To recipients
    */
    'to': Array<string>;
    /**
    * CC recipients
    */
    'cc'?: Array<string>;
    /**
    * BCC recipients
    */
    'bcc'?: Array<string>;
    'sender'?: Sender;
    'recipients'?: EmailRecipients;
    /**
    * Thread topic subject
    */
    'subject'?: string;
    /**
    * Created at DateTime
    */
    'createdAt': Date;
    /**
    * Updated at DateTime
    */
    'updatedAt': Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "inboxId",
            "baseName": "inboxId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "from",
            "baseName": "from",
            "type": "string",
            "format": ""
        },
        {
            "name": "to",
            "baseName": "to",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "cc",
            "baseName": "cc",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "bcc",
            "baseName": "bcc",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "sender",
            "baseName": "sender",
            "type": "Sender",
            "format": ""
        },
        {
            "name": "recipients",
            "baseName": "recipients",
            "type": "EmailRecipients",
            "format": ""
        },
        {
            "name": "subject",
            "baseName": "subject",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return EmailThreadDto.attributeTypeMap;
    }
    
    public constructor() {
    }
}

