/**
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.   ## Resources - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository 
 *
 * OpenAPI spec version: 6.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

/**
* Analysis result for email. Each verdict property is a string PASS|FAIL|GRAY or dynamic error message
*/
export class EmailAnalysis {
    /**
    * Verdict of DomainKeys Identified Mail analysis
    */
    'dkimVerdict'?: string;
    /**
    * Verdict of Domain-based Message Authentication Reporting and Conformance analysis
    */
    'dmarcVerdict'?: string;
    /**
    * Verdict of spam ranking analysis
    */
    'spamVerdict'?: string;
    /**
    * Verdict of Send Policy Framework record spoofing analysis
    */
    'spfVerdict'?: string;
    /**
    * Verdict of virus scan analysis
    */
    'virusVerdict'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "dkimVerdict",
            "baseName": "dkimVerdict",
            "type": "string",
            "format": ""
        },
        {
            "name": "dmarcVerdict",
            "baseName": "dmarcVerdict",
            "type": "string",
            "format": ""
        },
        {
            "name": "spamVerdict",
            "baseName": "spamVerdict",
            "type": "string",
            "format": ""
        },
        {
            "name": "spfVerdict",
            "baseName": "spfVerdict",
            "type": "string",
            "format": ""
        },
        {
            "name": "virusVerdict",
            "baseName": "virusVerdict",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return EmailAnalysis.attributeTypeMap;
    }
    
    public constructor() {
    }
}

