/**
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * OpenAPI spec version: 6.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

/**
* Options for exporting user data
*/
export class ExportOptions {
    'outputFormat': ExportOptionsOutputFormatEnum;
    'excludePreviouslyExported'?: boolean;
    'createdEarliestTime'?: Date;
    'createdOldestTime'?: Date;
    'filter'?: string;
    'listSeparatorToken'?: any;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "outputFormat",
            "baseName": "outputFormat",
            "type": "ExportOptionsOutputFormatEnum",
            "format": ""
        },
        {
            "name": "excludePreviouslyExported",
            "baseName": "excludePreviouslyExported",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "createdEarliestTime",
            "baseName": "createdEarliestTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "createdOldestTime",
            "baseName": "createdOldestTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "filter",
            "baseName": "filter",
            "type": "string",
            "format": ""
        },
        {
            "name": "listSeparatorToken",
            "baseName": "listSeparatorToken",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ExportOptions.attributeTypeMap;
    }
    
    public constructor() {
    }
}


export type ExportOptionsOutputFormatEnum = "CSV_DEFAULT" | "CSV_EXCEL" ;

