/**
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * OpenAPI spec version: 6.5.2
 * Contact: contact@mailslurp.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StructuredOutputSchema } from './StructuredOutputSchema.ts';
import { HttpFile } from '../http/http.ts';

/**
* Options for generating structured content output from an email
*/
export class GenerateStructuredContentEmailOptions {
    /**
    * Email ID to read and pass to AI
    */
    'emailId': string;
    /**
    * Content selector to select part of email to operate on
    */
    'contentSelector'?: GenerateStructuredContentEmailOptionsContentSelectorEnum;
    /**
    * Optional instructions for the AI to follow. Try to be precise and clear. You can include examples and hints.
    */
    'instructions'?: string;
    'outputSchema': StructuredOutputSchema;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "emailId",
            "baseName": "emailId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "contentSelector",
            "baseName": "contentSelector",
            "type": "GenerateStructuredContentEmailOptionsContentSelectorEnum",
            "format": ""
        },
        {
            "name": "instructions",
            "baseName": "instructions",
            "type": "string",
            "format": ""
        },
        {
            "name": "outputSchema",
            "baseName": "outputSchema",
            "type": "StructuredOutputSchema",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GenerateStructuredContentEmailOptions.attributeTypeMap;
    }
    
    public constructor() {
    }
}


export type GenerateStructuredContentEmailOptionsContentSelectorEnum = "RAW" | "BODY" ;

