/**
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * OpenAPI spec version: 6.5.2
 * Contact: contact@mailslurp.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class PhonePlanAvailabilityItem {
    'phoneCountry': PhonePlanAvailabilityItemPhoneCountryEnum;
    'availabilityStatus': PhonePlanAvailabilityItemAvailabilityStatusEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "phoneCountry",
            "baseName": "phoneCountry",
            "type": "PhonePlanAvailabilityItemPhoneCountryEnum",
            "format": ""
        },
        {
            "name": "availabilityStatus",
            "baseName": "availabilityStatus",
            "type": "PhonePlanAvailabilityItemAvailabilityStatusEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PhonePlanAvailabilityItem.attributeTypeMap;
    }
    
    public constructor() {
    }
}


export type PhonePlanAvailabilityItemPhoneCountryEnum = "US" | "GB" | "AU" ;
export type PhonePlanAvailabilityItemAvailabilityStatusEnum = "AVAILABLE" | "NON_MATCHING_SUBSCRIPTION_CURRENCY" | "NON_MATCHING_SUBSCRIPTION_TYPE" | "ALREADY_ASSIGNED" ;

