/**
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * OpenAPI spec version: 6.5.2
 * Contact: contact@mailslurp.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

/**
* Structured output schema to use for generation
*/
export class StructuredOutputSchema {
    'anyOf'?: Array<StructuredOutputSchema>;
    '_default'?: any;
    'description'?: string;
    '_enum'?: Array<string>;
    'example'?: any;
    'format'?: string;
    'items'?: StructuredOutputSchema;
    'maxItems'?: number;
    'minItems'?: number;
    'maxLength'?: number;
    'minLength'?: number;
    'pattern'?: string;
    'properties'?: { [key: string]: StructuredOutputSchema; };
    'propertyOrdering'?: Array<string>;
    'required'?: Array<string>;
    'maxProperties'?: number;
    'minProperties'?: number;
    'maximum'?: number;
    'minimum'?: number;
    'nullable'?: boolean;
    'title'?: string;
    /**
    * Primitive JSON schema types with a fallback CUSTOM for unknown values.
    */
    'type'?: StructuredOutputSchemaTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "anyOf",
            "baseName": "anyOf",
            "type": "Array<StructuredOutputSchema>",
            "format": ""
        },
        {
            "name": "_default",
            "baseName": "default",
            "type": "any",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "_enum",
            "baseName": "enum",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "example",
            "baseName": "example",
            "type": "any",
            "format": ""
        },
        {
            "name": "format",
            "baseName": "format",
            "type": "string",
            "format": ""
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "StructuredOutputSchema",
            "format": ""
        },
        {
            "name": "maxItems",
            "baseName": "maxItems",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "minItems",
            "baseName": "minItems",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "maxLength",
            "baseName": "maxLength",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "minLength",
            "baseName": "minLength",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "pattern",
            "baseName": "pattern",
            "type": "string",
            "format": ""
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "{ [key: string]: StructuredOutputSchema; }",
            "format": ""
        },
        {
            "name": "propertyOrdering",
            "baseName": "propertyOrdering",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "required",
            "baseName": "required",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "maxProperties",
            "baseName": "maxProperties",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "minProperties",
            "baseName": "minProperties",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "maximum",
            "baseName": "maximum",
            "type": "number",
            "format": ""
        },
        {
            "name": "minimum",
            "baseName": "minimum",
            "type": "number",
            "format": ""
        },
        {
            "name": "nullable",
            "baseName": "nullable",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "StructuredOutputSchemaTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return StructuredOutputSchema.attributeTypeMap;
    }
    
    public constructor() {
    }
}


export type StructuredOutputSchemaTypeEnum = "string" | "number" | "integer" | "boolean" | "object" | "array" | "null" ;

