/**
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * OpenAPI spec version: 6.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class WebhookResultDto {
    'createdAt': Date;
    'httpMethod': WebhookResultDtoHttpMethodEnum;
    'id'?: string;
    'inboxId': string;
    'messageId': string;
    'redriveId'?: string;
    'responseBodyExtract'?: string;
    'responseStatus'?: number;
    'responseTimeMillis': number;
    'resultType'?: WebhookResultDtoResultTypeEnum;
    'seen'?: boolean;
    'updatedAt': Date;
    'userId': string;
    'webhookEvent': WebhookResultDtoWebhookEventEnum;
    'webhookId': string;
    'webhookUrl': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "httpMethod",
            "baseName": "httpMethod",
            "type": "WebhookResultDtoHttpMethodEnum",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "inboxId",
            "baseName": "inboxId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "messageId",
            "baseName": "messageId",
            "type": "string",
            "format": ""
        },
        {
            "name": "redriveId",
            "baseName": "redriveId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "responseBodyExtract",
            "baseName": "responseBodyExtract",
            "type": "string",
            "format": ""
        },
        {
            "name": "responseStatus",
            "baseName": "responseStatus",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "responseTimeMillis",
            "baseName": "responseTimeMillis",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "resultType",
            "baseName": "resultType",
            "type": "WebhookResultDtoResultTypeEnum",
            "format": ""
        },
        {
            "name": "seen",
            "baseName": "seen",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "webhookEvent",
            "baseName": "webhookEvent",
            "type": "WebhookResultDtoWebhookEventEnum",
            "format": ""
        },
        {
            "name": "webhookId",
            "baseName": "webhookId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "webhookUrl",
            "baseName": "webhookUrl",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WebhookResultDto.attributeTypeMap;
    }
    
    public constructor() {
    }
}


export type WebhookResultDtoHttpMethodEnum = "GET" | "HEAD" | "POST" | "PUT" | "PATCH" | "DELETE" | "OPTIONS" | "TRACE" ;
export type WebhookResultDtoResultTypeEnum = "BAD_RESPONSE" | "EXCEPTION" | "SUCCESS" ;
export type WebhookResultDtoWebhookEventEnum = "EMAIL_RECEIVED" | "NEW_EMAIL" | "NEW_CONTACT" | "NEW_ATTACHMENT" | "EMAIL_OPENED" | "EMAIL_READ" ;

