/**
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * OpenAPI spec version: 6.5.2
 * Contact: contact@mailslurp.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Set } from './Set.ts';
import { HttpFile } from '../http/http.ts';

/**
* NEW_CONTACT webhook payload. Sent to your webhook url endpoint via HTTP POST when an email is received by the inbox that your webhook is attached to that contains a recipient that has not been saved as a contact.
*/
export class WebhookNewContactPayload {
    /**
    * Idempotent message ID. Store this ID locally or in a database to prevent message duplication.
    */
    'messageId'?: string;
    /**
    * ID of webhook entity being triggered
    */
    'webhookId'?: string;
    /**
    * Name of the webhook being triggered
    */
    'webhookName'?: string;
    /**
    * Name of the event type webhook is being triggered for.
    */
    'eventName'?: WebhookNewContactPayloadEventNameEnum;
    'contactId'?: string;
    'groupId'?: string;
    'firstName'?: string;
    'lastName'?: string;
    'company'?: string;
    'primaryEmailAddress'?: string;
    'emailAddresses'?: Set<string>;
    'tags'?: Set<string>;
    'metaData'?: any;
    'optOut'?: boolean;
    'createdAt'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "messageId",
            "baseName": "messageId",
            "type": "string",
            "format": ""
        },
        {
            "name": "webhookId",
            "baseName": "webhookId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "webhookName",
            "baseName": "webhookName",
            "type": "string",
            "format": ""
        },
        {
            "name": "eventName",
            "baseName": "eventName",
            "type": "WebhookNewContactPayloadEventNameEnum",
            "format": ""
        },
        {
            "name": "contactId",
            "baseName": "contactId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "groupId",
            "baseName": "groupId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "firstName",
            "baseName": "firstName",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastName",
            "baseName": "lastName",
            "type": "string",
            "format": ""
        },
        {
            "name": "company",
            "baseName": "company",
            "type": "string",
            "format": ""
        },
        {
            "name": "primaryEmailAddress",
            "baseName": "primaryEmailAddress",
            "type": "string",
            "format": ""
        },
        {
            "name": "emailAddresses",
            "baseName": "emailAddresses",
            "type": "Set<string>",
            "format": ""
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Set<string>",
            "format": ""
        },
        {
            "name": "metaData",
            "baseName": "metaData",
            "type": "any",
            "format": ""
        },
        {
            "name": "optOut",
            "baseName": "optOut",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return WebhookNewContactPayload.attributeTypeMap;
    }
    
    public constructor() {
    }
}


export type WebhookNewContactPayloadEventNameEnum = "EMAIL_RECEIVED" | "NEW_EMAIL" | "NEW_CONTACT" | "NEW_ATTACHMENT" | "EMAIL_OPENED" | "EMAIL_READ" ;

